### ISSUE TITLE
Comparison to ResUNet++

### ISSUE THREAD

**Issue by Mano3** [DebeshJha/2020-CBMS-DoubleU-Net#3]
Hi, you have mentioned in your paper ResUNet++, which is also your work.
Also, I've seen that you are working on ResUNet++ + CRF + TTA.
Can you make a comparison between the 3 on the presented datasets?
Is any one of these models superior to the others?
Thanks.

**Comment by DebeshJha** [comment]
Hi, 

Thanks for your query. The combination of ResUNet++, CRF, and TTA is data-dependent. However, I would prefer "ResUNet++, +CRF+ TTA" as they perform well on the cross-dataset or generalizability test.
